[package]
name = "cucumber_server"
version = "0.1.0"
authors = ["Alex McArther <acmcarther@gmail.com>"]

[dependencies]
serde_json = "*"
cucumber_runner = { path = "../runner" }
cucumber_event = { path = "../event" }
