language: rust
sudo: false

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

before_install:
  - rvm install ruby-2.2.3
  - rvm use 2.2.3
  - bundle install

after_success:
  - travis-cargo doc-upload

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
  allow_failures:
    - rust: beta
    - rust: nightly

script:
  # TODO: Clean this up: it needs to be exposed as a single command for developers
  - (cd ./src/definitions && travis-cargo test)
  - (cd ./src/event && travis-cargo test)
  - (cd ./src/regex && travis-cargo test)
  - (cd ./src/runner && travis-cargo test)
  - (cd ./src/server && travis-cargo test)
  - (cd ./src/state && travis-cargo test)

  - travis-cargo test

  - (cd ./examples/simple && travis-cargo test)
  - (cd ./examples/calculator && travis-cargo test)

  - travis-cargo doc -- -j 1


cache:
  bundler: true
  directories:
    - $HOME/.cargo/
