language: rust
sudo: false

before_install:
  - rvm install ruby-2.2.3
  - rvm use 2.2.3
  - bundle install

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly

script:
   - cargo test

   # Bootstrap example's cache with cucumber's cache
   - cp ./target/ ./examples/calculator/target/ -r

   - cd ./examples/calculator && cargo test


cache:
  bundler: true
  directories:
    - $HOME/.cargo/
    # TODO: cache /target when per-compiler caching is available
