language: rust
sudo: false

before_install:
  - rvm install ruby-2.2.3
  - rvm use 2.2.3
  - bundle install

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
  allow_failures:
    - rust: beta
    - rust: nightly

script:
   # Run Submodule unit tests
   # TODO: Clean this up: it needs to be exposed as a single command for developers
   - (cd ./src/definitions && cargo test)
   - (cd ./src/event && cargo test)
   - (cd ./src/regex && cargo test)
   - (cd ./src/runner && cargo test)
   - (cd ./src/server && cargo test)
   - (cd ./src/state && cargo test)

   - cargo test

   - (cd ./examples/simple && cargo test)
   - (cd ./examples/calculator && cargo test)


cache:
  bundler: true
  directories:
    - $HOME/.cargo/
    # TODO: cache /target when per-compiler caching is available
