language: rust
sudo: false

before_install:
  - rvm install ruby-2.2.3
  - rvm use 2.2.3
  - bundle install

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly

script:
   - cargo test
   - cd ./examples/calculator; cargo test
