[package]
name = "cucumber"
version = "0.1.0"
authors = ["Alex McArther <acmcarther@gmail.com>"]

[dependencies]
regex = "*"
hyper = "*"
rustc-serialize = "*"

[[example]]
name = "calculator"
path = "examples/calculator/features/cuke.rs"
