[package]
name = "cucumber"
version = "0.1.0"
authors = ["Alex McArther <acmcarther@gmail.com>"]
build = "build.rs"

[features]
default = ["serde_codegen"]
nightly = ["serde_macros"]

[build-dependencies]
serde_codegen = { version = "0.7.0", optional = true }
syntex = "0.29.0"
itertools = "*"

[dependencies]
itertools = "*"
regex = "*"
hyper = "*"
serde = "0.7.0"
serde_json = "0.7.0"
serde_macros = { version = "0.7.0", optional = true }

[[example]]
name = "calculator"
path = "./examples/calculator/features/cuke.rs"

[[example]]
name = "cuke"
path = "./features/cuke.rs"
