[package]
name = "cucumber_runner"
version = "0.1.0"
authors = ["Alex McArther <acmcarther@gmail.com>"]

[dependencies]
regex = "*"
cucumber_definitions = { path = "../definitions" }
cucumber_state = { path = "../state" }
cucumber_event = { path = "../event" }
